### ISSUE TITLE
Problems building Shepherd

### ISSUE THREAD

**Issue by gurkennase** [ffont/shepherd#1]
I followed the instructions in README.md on a mini Mac 12.5.1 and Xcode and on a Raspberry Pi 2 B. 
-Both builds could not find the openssl/*.h files (I added the absolute path with every file that couldn't be found)
-Both put out that inline variables are available with C++17 (I accidentally found where to switch that in Xcode, Idon't know how to fix it on a Raspberry Pi)
-Xcode said that the Type of Variable scope_id was forced to change into an other Type (sorry, didn't take a Screenshot)
There was one more issue I forgot (Couldn't find/open a file)
For I changed rights and ownerships, path and more I restored the Mac with a backup to fix that. 
Maybe you can help?
Thanks! Gurkennase

**Comment by ffont** [comment]
Hi,

Nice to see that someone is trying to build this :)
Note that support will be very limited but I can try to help.
About the inline variables I get these warnings as well and I just ignore them. I wander if the scope_id issue is also a warning or an error, if only a warning I ignore as well.

About the openssl files, it could be that openssl dependency can be removed, but I'm not sure now. In any case it should work if you have openssl installed here `/usr/local/opt/openssl/include` (includes) and `/usr/local/opt/openssl/lib` (lib). I guess I installed with brew (?). I don't remember having had problems with that.

Anyway, please copy here any errors so I can probably help more.

Cheers,

**Comment by gurkennase** [comment]
Hi Frederic

Thank you for the prompt reaction - I’m glad.

Brew didn’t install openssl into the mentioned directories (/usr/local/….). No way
It was installed here:
***@***.***/3.0.5/include/openssl/
And
***@***.***/3.0.5/

I found a guy dying a symbolic link could fix it. So I went:
Mac-mini-von-Stephan:~ root# ln -s ***@***.***/3.0.5/include/openssl/ /usr/local/opt/openssl/include/
Mac-mini-von-Stephan:~ root# ln -s ***@***.***/3.0.5/lib/libssl.3.dylib /usr/local/lib/
Mac-mini-von-Stephan:~ root# ln -s ***@***.***/3.0.5/lib/libssl.dylib /usr/local/lib/
I had to make the dirs /opt/openssl/include/ in /usr/local/

That’s where I am right now.

I did a backup und will start Xcode now. Btw: 
What does "compile as a normal JUCE project“	mean?

Cheers

**Comment by gurkennase** [comment]
Hi Frederic

This time none of the latter errors occurred :-)
There were 8 Errors about missing Juce Files (see attached file)

Thanks in advance!

Stephan

**Comment by ffont** [comment]
Hi,

I think you forgot to link the attached file as I can't access any. "compile as a normal JUCE project“ is a bit vague, it means that you open the XCode project and hit the big "play" button to compile. But you need to have checked out the git submodules to get JUCE source code  (the `git submodule update --init` command).

frederic

**Comment by ffont** [comment]
I'll close this issue as there have been many changes since then with instructions updated.
